### ISSUE TITLE
Fail to reboot with ARM/IAR

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/mbed-bootloader#3] opened 2018-05-15 07:01 UTC
I build `mbed-bootloader` by:
`
mbed compile -m K64F -t ARM --profile tiny.json
`
Or:
`
mbed compile -m K64F -t IAR --profile tiny.json
`
At first boot, I can see log meessage:
```
[BOOT] mbed Bootloader
[BOOT] ARM: 0000000000000000000000000000000000000000
[BOOT] OEM: 0000000000000000000000000000000000000000
[BOOT] Layout: 0 9420
[BOOT] Active firmware integrity check:
[ERR ] Active firmware integrity check failed
```
But I see none after reboot.

If I flash attached K64F bootloader `tools`/`mbed-bootloader-k64f-block_device-sotp-v3_3_0.bin` in `mbed-cloud-client-example` (1.3.1.1), reboot is OK:
```
[BOOT] mbed Bootloader
[BOOT] ARM: 74CE36607E38CD63ECDD72CE2F1262D58BF55448
[BOOT] OEM: 0000000000000000000000000000000000000000
[BOOT] Layout: 0 7188
[BOOT] Active firmware integrity check:
[ERR ] Active firmware integrity check failed
[BOOT] Slot 0 is empty
[ERR ] Active firmware invalid
[ERR ] Failed to jump to application!
[BOOT] mbed Bootloader
[BOOT] ARM: 74CE36607E38CD63ECDD72CE2F1262D58BF55448
[BOOT] OEM: 0000000000000000000000000000000000000000
[BOOT] Layout: 0 7188
[BOOT] Active firmware integrity check:
[ERR ] Active firmware integrity check failed
[BOOT] Slot 0 is empty
[ERR ] Active firmware invalid
[ERR ] Failed to jump to application!
```

**Target**
K64F

**ARM Toolchain**
5.24

**GCC_ARM Toolchain**
GNU Tools for Arm Embedded Processors 7-2017-q4-major

**IAR Toolchain**
7.8

**mbed-bootloader**
v3.3.0

**mbed-os**
5.8.4

**Comment by LiyouZhou** [comment] 2018-07-30 11:37
with ARMCC or IAR the binary size of the bootloader would be too large. But I cannot explain why you would fail to reboot as the bootloader should not be doing any writing.

**Comment by ccli8** [comment] 2018-07-31 02:01
@LiyouZhou Yes, with ARM/IAR, the binary size of bootloader exceeds 32KiB. I suggest adjusting `mbed_app.json` to make all GCC/ARM/IAR compiled binary workable. It is confusing that just GCC-compiled binary can work.

**Comment by SeppoTakalo** [comment] 2019-11-22 11:54
I'm closing this, as the issue is outdated.
We have made a choice to use only GCC for building our bootloaders.

Functionality should work on all compilers, but the size vary, so we only fine tune for one compiler, if required.

**Closed by SeppoTakalo** 2019-11-22 11:54 UTC
